name: Build and push to Docker Hub

on:
  push:
    branches: [ "ubuntu" ]
  pull_request:
    branches: [ "ubuntu" ]

env:
  REGISTRY_IMAGE: vincejv/handbrake

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
        march:
          - sandybridge
          - ivybridge
          - haswell
          - broadwell
          - alderlake
          - raptorlake
          - rocketlake
          - skylake
          - x86-64-v2
          - x86-64-v3
          - x86-64-v4
          - x86-64
          - znver1
          - znver2
          - znver3
          - znver4
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            # set latest tag for default branch
            type=raw,value=${{ matrix.march }}-ubuntu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retrieve commit
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: |
            MARCH=${{ matrix.march }}
            HB_BUILD=${{ steps.commit.outputs.short }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: | 
            ${{ env.REGISTRY_IMAGE }}:${{ matrix.march }}-ubuntu
            ${{ env.REGISTRY_IMAGE }}:${{ matrix.march }}-ubuntu-${{ steps.commit.outputs.short }}
            ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ matrix.march }}-ubuntu
            ghcr.io/${{ env.REGISTRY_IMAGE }}:${{ matrix.march }}-ubuntu-${{ steps.commit.outputs.short }}