name: Build and push to Docker Hub

on:
  push:
    branches: [ "mac" ]
  pull_request:
    branches: [ "mac" ]

env:
  HANDBRAKE_VERSION: 1.7.3
  HANDBRAKE_DEBUG_MODE: none

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      commit: ${{ steps.commit.outputs.short }}
      new_tag: ${{ steps.tag_version.outputs.new_tag }}
      changelog: ${{ steps.tag_version.outputs.changelog }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get commit hash
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Bump version and calculate tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: true
  build:
    runs-on: macos-13
    needs:
      - versioning
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Retrieve commit
        id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Install GNU sed
        run: |
          brew update
          brew install gnu-sed
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      - name: Toolchain Cache
        id: mac-toolchain
        uses: actions/cache@v4
        with:
          path: ~/mac-toolchain
          key: ${{ runner.os }}-${{ runner.arch }}-toolchain-${{ hashFiles('**/scripts/mac-toolchain-build') }}
      - name: Cargo-C Toolchain Cache
        id: mac-cargo-c-toolchain
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/cargo-capi
            ~/.cargo/bin/cargo-cbuild
            ~/.cargo/bin/cargo-cinstall
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-c-toolchain
      - name: Setup Environment
        run: |
          echo ~/mac-toolchain/bin >> $GITHUB_PATH
          rustup target add aarch64-apple-darwin
      - name: Setup Toolchain
        if: steps.mac-toolchain.outputs.cache-hit != 'true'
        run: |
          pip install setuptools
          scripts/mac-toolchain-build ~/mac-toolchain
      - name: Setup Cargo-C Toolchain
        if: steps.mac-cargo-c-toolchain.outputs.cache-hit != 'true'
        run: |
          cargo install cargo-c
      - name: Build handbrake
        run: |
          src/handbrake/build.sh \
            ${{ env.HANDBRAKE_VERSION }} \
            https://github.com/HandBrake/HandBrake/releases/download/${{ env.HANDBRAKE_VERSION }}/HandBrake-${{ env.HANDBRAKE_VERSION }}-source.tar.bz2 \
            ${{ env.HANDBRAKE_DEBUG_MODE }} \
            ${{ steps.commit.outputs.short }}
      # - name: Upload as mac package artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mac-pkg
      #     path: /tmp/handbrake/build/pkg
      #     if-no-files-found: error
      #     retention-days: 90
      # - name: Upload binaries to release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "/tmp/handbrake/build/pkg"
      #     makeLatest: false

  # merge:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build
  #   steps:
  #     - name: Get commit hash
  #       id: commit
  #       uses: prompt/actions-commit-hash@v3
  #     - name: Bump version and push tag
  #       id: tag_version
  #       uses: mathieudutour/github-tag-action@v6.2
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Github release
  #       uses: ncipollo/release-action@v1
  #       with:
  #         tag: ${{ steps.tag_version.outputs.new_tag }}
  #         name: Release ${{ steps.commit.outputs.short }}
  #         body: ${{ steps.tag_version.outputs.changelog }}
  #         artifacts: "/tmp/handbrake/build/libhb/*.dll,/tmp/handbrake/build/HandBrakeCLI.exe"
